spring.application.name=contactForm
# Datasource (PostgreSQL Superbase)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.leak-detection-threshold=0
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Table Validation
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# Resend API Configuration
resend.api.key=${RESEND_API_KEY}
# Ocultar logs para proteger credenciales
logging.level.org.hibernate.orm.connections.pooling=WARN
# Credenciales de Notion
notion.api.token=${NOTION_API_TOKEN}
notion.database.id=${NOTION_DATABASE_ID}
notion.api.version=2022-06-28